name: buildDeploy
on: push

jobs:
  buildDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore & ache lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm i --no-package-lock

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/feat-**'
        run: npm run deploy:staging

      - name: Deploy to Dev
        if: github.ref == 'refs/heads/develop'
        run: npm run deploy:dev

      - name: Deploy to Prod and tag release
        if: github.ref == 'refs/heads/master'
        env:
          GH_TOKEN: ${{ github.token }}
        run: npm run deploy:prod
